### PR TITLE
Remove iframe

### PR DESCRIPTION
**Pull request by elmaxe**

### CODE REVIEW

**Review by niklasvatn — CHANGES_REQUESTED** [review]
https://github.com/datasektionen/cashflow/blob/remove-iframe/expenses/models.py

```
    def is_image(self):
        file_regex = re.compile(".*\.(jpg|jpeg|png|gif|bmp)", re.IGNORECASE)
        return file_regex.match(self.file.name)
```

I guess this doesn't solve the issue. I can still upload an arbitrary file with jpg as file extension.

**Comment by oskstr** [comment]
> https://github.com/datasektionen/cashflow/blob/remove-iframe/expenses/models.py
> 
> ```python
>     def is_image(self):
>         file_regex = re.compile(".*\.(jpg|jpeg|png|gif|bmp)", re.IGNORECASE)
>         return file_regex.match(self.file.name)
> ```
> 
> I guess this doesn't solve the issue. I can still upload an arbitrary file with jpg as file extension.

@niklasvatn those didn't use use iframes to begin with, right? We just try to render an `` in those cases which I think should be fairly safe.

**Comment by elmaxe** [comment]
> > https://github.com/datasektionen/cashflow/blob/remove-iframe/expenses/models.py
> > ```python
> >     def is_image(self):
> >         file_regex = re.compile(".*\.(jpg|jpeg|png|gif|bmp)", re.IGNORECASE)
> >         return file_regex.match(self.file.name)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I guess this doesn't solve the issue. I can still upload an arbitrary file with jpg as file extension.
> 
> @niklasvatn those didn't use use iframes to begin with, right? We just try to render an `` in those cases which I think should be fairly safe.

Correct, iframes were only used for pdfs

**Comment by niklasvatn** [comment]
Right, what happens if we try to load an arbitrary file in an ``-tag?

**Comment by oskstr** [comment]
You would probably just see a broken image, it wouldn't run any code. Unless I'm missing something. I tried to read up on vulnerabilities and the HTML spec for `` but it looks like it doesn't specify which type of files should be supported, it is up to the browser. The browser would try to decode the image and if it fails to covert it to a bitmap it can run an `onerror` function which we haven't set here.

The removal of the iframe would probably remove the ability to view pdfs and we might want to look into safe alternatives for that. Also conceivable to receive in `.html` format if you get a receipt in the form of an email.

**Comment by Herkarl** [comment]
I don't remember the exact extent of the security problem, but pehaps adding the [`sandbox`](https://www.w3schools.com/tags/att_iframe_sandbox.asp) attribute to the `iframe` would be enough?

**Comment by elmaxe** [comment]
Fixed in https://github.com/datasektionen/cashflow/pull/127

**Pull request closed without merging**
