### PR TITLE
Remove infinte money glitch

### LINKED ISSUE #176: 🚨🚨🚨 Double payments must be prevented! 🚨🚨🚨
When clicking the pay button, the server apparently does not check if the payment has already been payed.

This is literally the infinite money glitch we've always needed, don't fix it!!!

### PR DESCRIPTION
**Pull request by foodelevator**
Fixes #176

Tested and it actually works. No error message though but that's a theme throughout the entirety of cashflow so that's not really relevant (:

### CODE REVIEW

**Comment by frblo** [comment]
I min mjukvaruutvecklingskurs säger de att man MÅSTE skapa fler tester som visar att man har löst problemet om man hittar en bug. Var är alla tester huh??

**Review by Herkarl — APPROVED** [review]
Tested locally and seems to work for me :+1: 

Dislike the lack of error message but oh well :stuck_out_tongue:, I suppose it is fine enough since it is an extreme edge case, and accidentally paying double is worse than the user being a bit confused. 
But I guess it could lead to some time being wasted and some kassör being a bit panicked while trying to figure out why a payment failed but still disappeared from the list when reloading the page.

I find it kinda unintuitive that the payment is marked as done when pressing "betala ut valda" instead of "Klar", but I suppose it has worked until now, and it works in favour for this fix, so eh :p

**Comment by foodelevator** [comment]
Yes I also noticed that before. It seems pretty dangerous as it would make sense that if you don't press "klar" it wouldn't be marked as payed so it could leave someone without being reimbursed some time.

**Comment by foodelevator** [comment]
> I min mjukvaruutvecklingskurs säger de att man MÅSTE skapa fler tester som visar att man har löst problemet om man hittar en bug. Var är alla tester huh?? 

Om jag kunde reagera med en 🤡 så hade jag

**Pull request merged**
